### ISSUE TITLE
Discrepancy with allele names?

### ISSUE THREAD

**Issue by davidbomze** [IgDAWG/BIGDAWG#1]
Getting "Discrepancy with allele names" error, although I'm using column names consistent with the sample data ('Data')

> colnames(HLA_data)
 [1] "SampleID" "Disease"  "A"        "A"        "DRB1"     "DRB1"     "DQB1"     "DQB1"     "DRB3"    
[10] "DRB3"     "DRB4"     "DRB4"     "DRB5"     "DRB5"

> colnames(my.data)
 [1] "SampleID" "Disease"  "A"        "A"        "B"        "B"        "C"        "C"        "DRB1"    
[10] "DRB1"     "DQB1"     "DQB1"     "DPB1"     "DPB1"

####################################
> bd.output <- BIGDAWG(my.data, HLA = TRUE,
                      Run.Tests = c("HWE","H","L","A"),
                      All.Pairwise = FALSE,
                      Trim = FALSE, Res = 2,
                      EVS.rm = FALSE, Cores.Lim = 1L,
                      Missing = 1,
                      Return = TRUE, Merge.Output = TRUE,
                      Results.Dir = "~/Downloads/HLA-temp/", Output = TRUE)
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
          BIGDAWG: Bridging ImmunoGenomic Data Analysis Workflow Gaps
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
BEGIN Analysis
DATA PROCESSING AND CHECKS.
Removing any missing data. This will affect Hardy-Weinberg Equilibrium test.
Running HLA specific check functions...
Running Amino Acid Analysis specific checks functions...
--Checking loci against IPD-IMGT/HLA Release: 3.29.0.
--Checking alleles against IPD-IMGT/HLA Release: 3.29.0.
*****ERROR!******
There may be a discrepancy with allele names. Unrecognized allele name(s) encountered. 
Problem alleles: A*- B*- C*- DRB1*- DQB1*- DPB1*- 
Error: Analysis stopped.

####################################

Any suggestions?

**Comment by pappasd** [comment]
Are you using the version on CRAN or from GitHub?

Derek

**Comment by davidbomze** [comment]
Both produce the same error.

Setting 'Missing' = 0 , doesn't result in this error and completes the command, but on the other hand does not yield any calculations at all - the output is pretty much 'NCalc' everywhere.

**Comment by pappasd** [comment]
Interesting. Ok. Would you be open to sharing the data set? It looks like
it's coming from the alleles not the col names. Feel free to
change/scramble sample IDs and phenotypes. I need to see how the alleles
are formatted and then I get try to fix whatever bug is creating the
problem.

Thanks.
Derek

**Comment by davidbomze** [comment]
Issue solved - changed all '-' to 'NA' in missing cells!

Thanks,
David

**Comment by pappasd** [comment]
Hmmm interesting. How were the empty cells formatted. As a "-" or as
something like this "HLA-A*-" because "-" should work? I'll have to try
that on my end, "-" is supposed an allowable NA character assuming it's the
only character in the cell.

D

**Comment by davidbomze** [comment]
Just standard "-".
You're welcome to try my table (attached).

[bd_input.txt](https://github.com/IgDAWG/BIGDAWG/files/1524773/bd_input.txt)
