### ISSUE TITLE
Data interpretation

### ISSUE THREAD

**Issue by Anahit19** [IgDAWG/BIGDAWG#1]
Dear Derek,

I am using the BIGDAWG package to run haplotype analysis for my HLA data.

As a result, for the alleles of C and B loci I have no significant association.

The only allele combination which differs is B3502 and C0401, which are supposed to be in linkage.

Could you please help with the output interpretation. What does the Inf OR mean? 

Also is it possible to conduct Ordinal regression analysis for three disease subgroups with your package?

Thank you very much,

Regards,
Anahit

**Comment by IgDAWG** [comment]
Hi Anahit, 

An OR value of _inf_ (meaning "infinity") for a given variant, which I think in your case is the `B*35:02~C*04:01` haplotype, means that there are no observations of that variant in the controls, so the OR value essentially too high for BIGDAWG to calculate (essentially infinite); think of it as akin to a divide-by-zero result on a calculator. Note that the upper bound of the 95% confidence interval will also be _inf_.

When there are no observations of a variant in the cases (and there are sufficient observations in controls to avoid binning) the OR value is 0. 

To illustrate this, I modified the `HLA_data` data frame bundled with BIGDAWG and set the number of `A33:01:01` alleles to 0 in controls, and the number of `DRB1*11:03` alleles to 0 in cases. 

Here is a marked-up and edited View() of the OR table for those results:
![image](https://user-images.githubusercontent.com/25827834/122826083-95cbfb00-d297-11eb-930e-3c94f0aa9b7e.png)

And here is a marked-up and edited View() of the table of counts: 

![image](https://user-images.githubusercontent.com/25827834/122826132-a2505380-d297-11eb-82ee-0e2b60a8e822.png)

I hope this helps interpret your BIGDAWG results. 

-- Steve Mack

**Comment by IgDAWG** [comment]
Oh. I should add that we don't currently have a regression function for BIGDAWG, but that will be coming in a release in the near future.

**Comment by Anahit19** [comment]
Thank you very much!
